Flight planner with H2 database
renvars/flight-planner pull request #1
Opened 2022-11-19 19:51 UTC by renvars

2022-11-21 18:06 UTC, renvars commented
Zinu jāpārtaisa, lai Airport ir kā atsevišķa tabula, sākumā to nevarēju galīgi atrast, tāpēc ir CorrectFlights ar to Airport un Flights ir ar String vērtībām.

2022-11-22 13:29 UTC, janistumpelis requested changes
Nu te gan ir šis tas jāpalabo, kā jau pats saproti. Mans ieteikums ar ko sākt:
Saliec validācijas anotācijas - tādā veidā tiksi vaļā no diezgan daudz koda.
Pagaidām slēdz datu bāzi nost, jo tas radījis nedaudz putru ar to Flights objektu, kurā ir pielikti klāt pa taisno Airport lauki. Dēļ tā arī ir padaudz lieka koda.
Kad tiksi ar šīm lietām galā, tad pārskatīšu vēlreiz.
Vēl ieteikums - labo pa mazam gabaliņam un ik pa laikam palaid atkal testus.

2022-11-22 13:29 UTC, janistumpelis commented on build.gradle
> +	testImplementation 'com.h2database:h2:2.1.214'
Kāpēc šis ir šeit?

2022-11-22 13:29 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/domain/Flights.java
> +public class Flights {
Nav korekti saukt daudzskaitlī, jo objekts reprezentē vienu flight nevis vairākus.

2022-11-22 13:29 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/Service/FlightsService.java
> +    private boolean validateData(CorrectFlight correctFlight) {
Validāciju taisi ar anotācijām nevis šādi manuāli.
Spring prezentācijā ir slaidi par validāciju un anotācijām, kas jāpieliek.

2022-11-22 13:29 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/Service/FlightsService.java
> +    private boolean validateAirports(Airport to, Airport from) {
Tas pats par anotācijām - ar tām varētu daudz vieglāk šo visu pārbaudīt nerakstot šo visu kodu.

2022-11-22 13:29 UTC, janistumpelis commented on src/main/java/io/codelex/flightplanner/domain/Flights.java
> +    private String departureTime;
Šie nebūtu jāglabā kā String - gan departureTime, gan arrivalTime jāglabā kā LocalDateTime.

2022-11-26 07:05 UTC, janistumpelis approved these changes

2022-11-27 19:39 UTC, merged